#!/usr/bin/env bash
# bash script that stops 4-to_infinity_and_beyond process.


echo "$BASHPID" > /var/run/myscript.pid

killthem() {
  rm /var/run/myscript.pid
  exit
}

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && killthem' SIGTERM
  trap 'killthem' SIGQUIT
done
